---
name: Validate Docs

"on":
  pull_request:
    branches:
      - main
    paths:
      - "modules/**"
      - "antora.yml"
      - "bin/validate-docs.sh"
      - "Makefile"

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit
          disable-telemetry: true

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install asciidoctor
        run: sudo gem install asciidoctor --no-document

      - name: Validate documentation
        run: make validate-docs
